spring:
  datasource:
    url: ${datasource.url}?createDatabaseIfNotExist=true
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    show-sql: true
bot:
  name: ${bot.name}
  token: ${bot.token}
jwt:
  secret: ${jwt.secret}